test modify the deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -182,7 +182,7 @@ setup() {
   local path=`config_get path`
   local repo=`config_get repo`
   run "mkdir -p $path/{shared/{logs,pids},source}"
-  test $? -eq 0 || abort setup paths failed
+  # test $? -eq 0 || abort setup paths failed
   log running setup
   log cloning $repo
   run "git clone $repo $path/source"
